### ISSUE TITLE
invalid value

### ISSUE THREAD

**Issue by image72** [stevelacy/pretty-metric#3]
`

prettyMetric(123.345).input('km').humanize();
=> "123.35km"
// correct value "0.12335km"
`
- add value Number.toFixed
- disable value Math.round keep accuracy
- add custom language unit like `KM: 千米`

**Comment by contra** [comment]
@image72 The default input unit is meter, but you change it to KM by specifying `.input('km')` - if you want your expected output you would just use `prettyMetric(123.345).humanize()`

**Comment by image72** [comment]
thanks a lot , but value not satisfactory.
I try to write custom function below
```javascript
const prettyMiles = (num, precision = 1, units) => {
  const addSpace = false;
  const UNITS = units || ["m", "km"];
  if (Math.abs(num) < 1) return num + (addSpace ? " " : "") + UNITS[0];
  const exponent = Math.min( Math.floor(Math.log10(num < 0 ? -num : num) / 3), UNITS.length - 1 );
  const toFixed = (number, fixed) => String(number).replace( new RegExp("(\\d*.)(\\d{" + fixed + "}).+"), "$1$2" );
  const n = toFixed( Number((num < 0 ? -num : num) / 1000 ** exponent), precision );
  return ( (num < 0 ? "-" : "") + n + (addSpace ? " " : "") + UNITS[exponent] );
};
// prettyMiles(1234567, 2)
// ==> 123.45km

```
